#!/usr/bin/perl
#################################################################################
#										#
# Build script for MXE11 images							#
# copyright (c) 2017-2018 Joerg Wolfram (joerg@jcwolfram.de)			#
#										#
#										#
# This program is free software; you can redistribute it and/or			#
# modify it under the terms of the GNU General Public License			#
# as published by the Free Software Foundation; either version 3		#
# of the License, or (at your option) any later version.			#
#										#
# This program is distributed in the hope that it will be useful,		#
# but WITHOUT ANY WARRANTY; without even the implied warranty of		#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the GNU		#
# General Public License for more details.					#
#										#
# You should have received a copy of the GNU General Public			#
# License along with this library; if not, write to the				#
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,			#
# Boston, MA 02111-1307, USA.							#
#										#
#################################################################################


$dummy=`cp disk1.bin image.bin`;
$dlen=(-s "disk1.bin");
print $dlen;
$zlen=((2436*1024)-$dlen)/512;
$cmd="dd if=/dev/zero bs=512 count=".$zlen.">dummy.bin";
$dummy=`$cmd`;
$dummy=`cat dummy.bin >> image.bin`;
$dummy=`rm -f dummy.bin`;

$dummy=`cat disk2.bin >> image.bin`;
$dlen=(-s "disk2.bin");
print $dlen;
$zlen=((2436*1024)-$dlen)/512;
$cmd="dd if=/dev/zero bs=512 count=".$zlen.">dummy.bin";
$dummy=`$cmd`;
$dummy=`cat dummy.bin >> image.bin`;
$dummy=`rm -f dummy.bin`;

$dummy=`cat disk3.bin >> image.bin`;
$dlen=(-s "disk3.bin");
print $dlen;
$zlen=((2436*1024)-$dlen)/512;
$cmd="dd if=/dev/zero bs=512 count=".$zlen.">dummy.bin";
$dummy=`$cmd`;
$dummy=`cat dummy.bin >> image.bin`;
$dummy=`rm -f dummy.bin`;

$dummy=`cp image.bin ../bin/image.bin`;
