#!/usr/bin/perl
#################################################################################
#										#
# Build script for native AVR programs						#
# copyright (c) 2009 Joerg Wolfram (joerg@jcwolfram.de)				#
#										#
#										#
# This program is free software; you can redistribute it and/or			#
# modify it under the terms of the GNU General Public License			#
# as published by the Free Software Foundation; either version 3		#
# of the License, or (at your option) any later version.			#
#										#
# This program is distributed in the hope that it will be useful,		#
# but WITHOUT ANY WARRANTY; without even the implied warranty of		#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the GNU		#
# General Public License for more details.					#
#										#
# You should have received a copy of the GNU General Public			#
# License along with this library; if not, write to the				#
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,			#
# Boston, MA 02111-1307, USA.							#
#										#
#################################################################################

$src = "../bin/image.bin";

$cmd="dd if=$src of=disk1.bin bs=512 count=4872";
$dummy=`$cmd`;

$cmd="dd if=$src of=disk2.bin bs=512 count=4872 skip=4872";
$dummy=`$cmd`;

$cmd="dd if=$src of=disk3.bin bs=512 count=4872 skip=9744";
$dummy=`$cmd`;

